### ISSUE TITLE
Suggested install command in readme doesn't work

### ISSUE THREAD

**Issue by Haprog** [open-wc/open-wc-starter-app#10]
This install command from the readme doesn't seem to work:
```
npm init @open-wc starter-app
```

Tested with:
```
> node --version && npm --version
v10.15.3
6.9.0
```

This is what happens:
```
> npm init @open-wc starter-app
npx: installed 29 in 4.719s
/Users/haprog/.npm/_npx/11755/lib/node_modules/@open-wc/create/node_modules/command-line-args/dist/index.js:1345
        throw err
        ^

UNKNOWN_VALUE: Unknown value: starter-app
    at commandLineArgs (/Users/haprog/.npm/_npx/11755/lib/node_modules/@open-wc/create/node_modules/command-line-args/dist/index.js:1342:21)
    at Object.<anonymous> (/Users/haprog/.npm/_npx/11755/lib/node_modules/@open-wc/create/dist/generators/app/index.js:76:48)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/haprog/.npm/_npx/11755/lib/node_modules/@open-wc/create/dist/create.js:12:14)
```

After some googling I found https://www.npmjs.com/package/@open-wc/create and it seems that it works if you just run:  
```
npm init @open-wc
```
and then select "Starter App" from the options it gives you.

**Comment by thepassle** [comment]
Thanks! Fixed in https://github.com/open-wc/open-wc-starter-app/commit/18e009ef4bc4c9cef9d12790e42c278c06ca0070 :)
